name: Build, sign and upload to Github Releases

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build, sign and upload to Github Releases
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Assemble release
      run: ./gradlew assembleRelease
    - uses: r0adkll/sign-android-release@v1
      name: Sign release
      id: sign_release
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        alias: ${{ secrets.KEYSTORE_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - uses: actions/upload-artifact@v2
      name: Upload APK
      with:
        name: Signed release APK
        path: ${{steps.sign_release.outputs.signedReleaseFile}}