name: Build, sign and upload to Github Releases

on:
  push:
    branches: [ release ]
  workflow_dispatch:

jobs:
  build:
    name: Build, sign and upload to Github Releases
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Assemble release
      run: ./gradlew assembleRelease
    - uses: r0adkll/sign-android-release@v1
      name: Sign release
      id: sign_release
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        alias: ${{ secrets.KEYSTORE_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Evaluate version name
      run: echo "VERSION_NAME=$(grep versionName app/build.gradle | cut -d \" -f2 | cut -d \" -f1)" >> $GITHUB_ENV
    - uses: svenstaro/upload-release-action@v2
      name: Upload APK to release
      with:
        file: ${{ steps.sign_release.outputs.signedReleaseFile }}
        tag: ${{ env.VERSION_NAME }}
        asset_name: prognoza-$tag.apk