name: Evaluate changelog

on:
  workflow_dispatch

jobs:
  test:
    name: Evaluate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: List dir structure
        run: ls
      - name: Evaluate version name
        run: |
          echo 'VERSION_NAME<<EOF' >> $GITHUB_ENV
          grep versionName app/build.gradle | cut -d \" -f2 | cut -d \" -f1 >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Evaluate changelog
        run: |
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          sed -n '/## \[${{ env.VERSION_NAME }}.*/,/## \[/p' app/CHANGELOG.md | head -n -2 >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Print changelog
        run: echo "$CHANGELOG"